# Generated by Django 4.1.7 on 2023-03-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Nebulosa', 'Nebulosa'), ('Estrela', 'Estrela'), ('Galáxia', 'Galáxia'), ('Planeta', 'Planeta')], default='', max_length=100),
        ),
    ]
